# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGallery < Formula
  desc "Generate a photography portfolio website for your photos"
  homepage "https://github.com/creekorful/go-gallery"
  version "0.17.1"
  license "GPL-3.0-only"

  on_macos do
    url "https://github.com/creekorful/go-gallery/releases/download/v0.17.1/go-gallery_0.17.1_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "eb37f9add3b008d5f650b6c7f6a5e7aacbfe9cfcaa244465ab646290052972c8"

    def install
      bin.install "go-gallery"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the GoGallery
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/creekorful/go-gallery/releases/download/v0.17.1/go-gallery_0.17.1_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "4baf3dd81c138904bab23558ee47ff93e92074b7994b7f6e488b20a30bb4f52b"

      def install
        bin.install "go-gallery"
      end
    end
  end

  test do
    system "#{bin}/go-gallery", "-h"
  end
end
