# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGallery < Formula
  desc "Generate a photography portfolio website for your photos"
  homepage "https://github.com/creekorful/go-gallery"
  version "0.14.0"
  license "GPL-3.0-only"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/creekorful/go-gallery/releases/download/v0.14.0/go-gallery_0.14.0_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "5330d2efdc1132ff7cb159d01f46828a026f5eeac88c57d24e06dcfe4d5d04c6"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/creekorful/go-gallery/releases/download/v0.14.0/go-gallery_0.14.0_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "5f6bde85b24c4dbe557ff172cb58e326c5e8c415a7645a2607a3f37f98ebb39e"
    end
  end

  def install
    bin.install "go-gallery"
  end

  test do
    system "#{bin}/go-gallery", "-h"
  end
end
