# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGallery < Formula
  desc "Generate a photography portfolio website for your photos"
  homepage "https://github.com/creekorful/go-gallery"
  version "0.16.2"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/creekorful/go-gallery/releases/download/v0.16.2/go-gallery_0.16.2_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "65dee2f54638435bdd7b0cab860a546685915bcc60f67e8ab376a5bd1507b782"

      def install
        bin.install "go-gallery"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/creekorful/go-gallery/releases/download/v0.16.2/go-gallery_0.16.2_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "7351be64ddac48837755075fe3116115119abc72b14fbf45ac2fe0cff28d4895"

      def install
        bin.install "go-gallery"
      end
    end
  end

  test do
    system "#{bin}/go-gallery", "-h"
  end
end
